[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['iceberg.vim']
hook_add = 'source ~/.config/nvim/rc/plugins/lightline.rc.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
