#
# Dein
#
[[plugins]]
repo = 'Shougo/dein.vim'


# Dependency
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
    call PluginConfig#Vimproc()
'''


#
# Git
#
[[plugins]]
repo = 'airblade/vim-gitgutter'


#
# Interface
#
[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['iceberg.vim']
hook_add = '''
    call PluginConfig#Lightline()
'''


#
# Utilities
#
[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
    nmap s <Nop>
    xmap s <Nop>
'''


#
# Colorscheme
#
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'
