# Plugins manager 'Dein'
[[plugins]]
repo = 'Shougo/dein.vim'

# Colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

# Status bar
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source $HOME/.vim/rc/plugins/lightline.rc.vim
'''

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Other utils
[[plugins]]
repo = 'machakann/vim-sandwich'
hook_add = '''
  nmap s <Nop>
  xmap s <Nop>

  let g:textobj#sandwich#stimeoutlen = 10
  let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
'''

[[plugins]]
repo = 'mattn/sonictemplate-vim'
