################################
# Edit utils
################################
[[plugins]]
repo = 'Shougo/unite.vim'
if = "!has('nvim')"
on_cmd = 'Unite'
depends = ['neomru.vim']
hook_source = '''
  source $HOME/.vim/rc/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
on_cmd = ['IndentLinesToggle']
hook_add = '''
  let g:loaded_indentLine = 1
'''

################################
# Programing utils
################################
[[plugins]]
repo = 'tyru/caw.vim'
on_map = ['<Plug>(caw:hatpos:toggle)', '<Plug>(caw.zeropos:toggle)']

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
on_ft = ['python']
hook_source = '''
  if has('nvim')
    source $XDG_CONFIG_HOME/nvim/rc/plugins/vimquickrun.rc.vim
  else
    source $HOME/.vim/rc/plugins/vimquickrun.rc.vim
  endif
'''


[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python', 'javascript', 'html', 'css', 'markdown', 'make', 'vim']
hook_source = '''
  if has('nvim')
    source $XDG_CONFIG_HOME/nvim/rc/plugins/ale.rc.vim
  else
    source $HOME/.vim/rc/plugins/ale.rc.vim
  endif
'''

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
on_ft = ['python']
hook_source = '''
  let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'janko-m/vim-test'
depends = ['vim-dispatch']
hook_source = '''
  let g:test#strategy = 'dispatch'
'''

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarToggle']
hook_add = '''
  let g:tagbar_sort = 0
  let g:tagbar_ase_insensitive = 1
  let g:tagbar_compact = 1
'''

################################
# Fuzzy Finder
################################
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
on_cmd = [
  'Files',
  'Gfiles?',
  'Tags',
]

################################
# Other utils
################################
# Completion of the brackets
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
on_ft = ['markdown']
hook_add = '''
  nmap <Leader>p :PrevimOpen<CR>
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
bulid = 'make'

# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden=1
  let NERDTreeIgnore = ['\.pyc$', '__pycache__']
  nmap <Leader>t <Plug>NERDTreetabsToggle<CR>
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
  let g:nerdtree_tabs_autofind = 0
  nmap <Leader>f <Plug>NERDTreeTabsFind<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = [
  'Git',
  'Gcommit',
  'Gstatus',
  'Gdiff',
  'Gblame',
  'Glog',
]
hook_add = '''
  nmap [figitive] <Nop>
  map <Leader>g [figitive]
  nmap <silent> [figitive]c :<C-u>Gcommit<CR>
  nmap <silent> [figitive]d :<C-u>Gdiff<CR>
  nmap <silent> [figitive]b :<C-u>Gblame<CR>
  nmap <silent> [figitive]l :<C-u>Glog<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = ['<Plug>(openbrowser-smart-search)']
hook_add = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap <Leader>b <Plug>(openbrowser-smart-search)
  vmap <Leader>b <Plug>(openbrowser-smart-search)
'''

################################
# Syntax
################################
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  let g:markdown_syntax_conceal = 0
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown']
hook_add = '''
  let g:table_mode_corner = '|'
  let g:table_mode_always_active = 1
  let g:table_mode_syntax = 1
  let g:table_mode_auto_align = 1
  let g:table_mode_map_prefix = '<LocalLeader>t'

  augroup TableCommands
    autocmd!
    autocmd Filetype markdown nmap <silent><LocalLeader>a :<C-u>TableModeRealign<CR>
    autocmd Filetype markdown nmap <silent><LocalLeader>t :<C-u>Tableize<CR>
  augroup END
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_souce = '''
  let g:vim_json_syntax_conceal = 0
  let g:indentLine_noConcealCursor = ""
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['markdown', 'toml', 'help']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
