# Plugins manager 'Dein'
[[plugins]]
repo = 'Shougo/dein.vim'

# Colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'romainl/Apprentice'

[[plugins]]
repo = 'dracula/vim'

# Status bar
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source $HOME/.vim/rc/plugins/lightline.rc.vim
'''

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Other utils
[[plugins]]
repo = 'mattn/sonictemplate-vim'
