#
# Edit utils
#
# Completion of the brackets
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1


#
# Programing utils
#
[[plugins]]
repo = 'tyru/caw.vim'
on_map = ['<Plug>(caw:hatpos:toggle)']
hook_add = '''
  " Add coment to beginning line (consider whitespace)
  nmap <Leader>c <Plug>(caw:hatpos:toggle)
  vmap <Leader>c <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python', 'javascript', 'html', 'css', 'markdown', 'make', 'vim']
hook_source = '''
  source $HOME/.vim/rc/plugins/ale.rc.vim
'''

# [[plugins]]
# repo = 'jsfaint/gen_tags.vim'
# on_ft = ['python', 'vim']
# hook_souce = '''
#   let g:gen_tags#ctags_auto_gen = 1
#   let g:gen_tags#gtags_auto_gen = 0
# '''

[[plugins]]
repo = 'janko-m/vim-test'
depends = ['vim-dispatch']
hook_source = '''
  let g:test#strategy = 'dispatch'
'''

[[plugins]]
repo = 'tpope/vim-dispatch'


#
# Fuzzy Finder
#
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
on_cmd = [
  'Files',
  'GFiles?',
  'Tags',
]
hook_add = '''
  " Keymap
  " Gig change files
  nnoremap <C-j><C-g> :<C-u>GFiles?<CR>
  " Gtags index
  nnoremap <C-j><C-]> :<C-u>Tags<CR>
  " My cli setting
  nnoremap <C-j><C-v> :<C-u>Files $HOME/.dotfiles<CR>
'''


#
# Other utils
#
[[plugins]]
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
on_ft = ['markdown']
hook_add = '''
  nmap <LocalLeader>p :PrevimOpen<CR>
'''

# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
on_map = ['<plug>NERDTreeTabsToggle', '<plug>NERDTreeTabsFind']
depends = ['nerdtree-git-plugin', 'vim-nerdtree-tabs']
hook_add = '''
  let NERDTreeShowHidden=1
  let NERDTreeIgnore=['\.pyc$', '__pycache__']
  nmap <Leader>tt <plug>NERDTreeTabsToggle<CR>
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
  let g:nerdtree_tabs_autofind = 0
  nmap <Leader>tf <plug>NERDTreeTabsFind<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = [
  'Git',
  'Gcommit',
  'Gstatus',
  'Gdiff',
  'Gblame',
  'Glog',
]
hook_add = '''
  " Prefix key
  nmap [figitive] <Nop>
  map <Leader>g [figitive]

  " Mappings
  nmap <silent> [figitive]b :<C-u>Gblame<CR>
  nmap <silent> [figitive]c :<C-u>Gcommit<CR>
  nmap <silent> [figitive]d :<C-u>Gdiff<CR>
  nmap <silent> [figitive]l :<C-u>Glog<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = ['<Plug>(openbrowser-smart-search)']
hook_add = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap <Leader>ob <Plug>(openbrowser-smart-search)
  vmap <Leader>ob <Plug>(openbrowser-smart-search)
'''


#
# Syntax
#
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  let g:markdown_syntax_conceal = 0
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown']
hook_add = '''
  let g:table_mode_corner = '|'
  let g:table_mode_always_active = 1
  let g:table_mode_syntax = 1
  let g:table_mode_auto_align = 1
  let g:table_mode_map_prefix = '<LocalLeader>t'

  augroup TableCommands
    autocmd!
    autocmd Filetype markdown nmap <silent><LocalLeader>ra :<C-u>TableModeRealign<CR>
    autocmd Filetype markdown nmap <silent><LocalLeader>t :<C-u>Tableize<CR>
  augroup END
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_souce = '''
  let g:vim_json_syntax_conceal = 0
  let g:indentLine_noConcealCursor = ""
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['markdown', 'toml', 'help']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
