[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'


# -----------------------------------------------------------------------------
# Deoplete
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/neosnippet-snippets'


# -----------------------------------------------------------------------------
# Git
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'


# -----------------------------------------------------------------------------
# Interface
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'call plugs#lightline#hook_add()'

[[plugins]]
repo = 'ryanoasis/vim-devicons'


# -----------------------------------------------------------------------------
# Utility
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'machakann/vim-sandwich'


# -----------------------------------------------------------------------------
# Colorscheme
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = 'Gautocmd VimEnter * nested colorscheme iceberg'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'raphamorim/lucario'

[[plugins]]
repo = 'dracula/vim'
