# -----------------------------------------------------------------------------
# Deoplete
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
build=':UpdateRemotePlugins'
hook_add = 'call plugs#deoplete#hook_source()'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
hook_source = 'call plugs#neosnippet#hook_source()'

# Sources
[[plugins]]
repo = 'zchee/deoplete-clang'
depends = ['deoplete.nvim']
on_ft = ['c', 'cpp', 'objc', 'objcpp']

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-go'
depends = ['deoplete.nvim']
on_ft = ['go']
# build = 'make'

[[plugins]]
repo = 'zchee/deoplete-docker'
depends = ['deoplete.nvim']
on_ft = ['dockerfile']

[[plugins]]
repo = 'zchee/deoplete-zsh'
depends = ['deoplete.nvim']
on_ft = ['sh', 'zsh']

[[plugins]]
repo = 'Shougo/neco-vim'
depends = ['deoplete.nvim']
on_ft = ['vim']


# -----------------------------------------------------------------------------
# Denite
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
build = ':UpdateRemotePlugins'
hook_source = 'call plugs#denite#hook_source()'

[[plugins]]
repo = 'Shougo/neomru.vim'


# -----------------------------------------------------------------------------
# Git
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Gblame', 'Gcommit', 'Gdiff', 'Ggrep', 'Glog', 'Gstatus']


# -----------------------------------------------------------------------------
# Linter
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'w0rp/ale'
on_ft = [
  'c', 'cpp', 'objc', 'objcpp',
  'python',
  'go',
  'dockerfile',
  'sh', 'bash',
  'vim',
]
hook_source = 'call plugs#ale#hook_source()'


# -----------------------------------------------------------------------------
# Utility
# -----------------------------------------------------------------------------
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'tyru/caw.vim'
on_map = ['<Plug>(caw:hatpos:toggle)']

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
on_cmd = 'QuickRun'
hook_source = 'call plugs#quickrun#hook_source()'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
on_cmd = 'Template'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['markdown', 'toml', 'help']
hook_add = '''
let g:precious_enable_switch_CursorMoved = {'*': 0, 'help': 1}
Gautocmd InsertEnter * :PreciousSwitch
Gautocmd InsertLeave * :PreciousReset
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = ['<Plug>(openbrowser-smart-search)']
hook_add = '''
let g:netrw_nogx = 1 " Disable netrw's gx mapping.
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = 'TagbarToggle'

# -----------------------------------------------------------------------------
# Language plugins
# -----------------------------------------------------------------------------
# Go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = 'call plugs#go#hook_source()'

# Python
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', 'djangohtml']

# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
let g:vim_markdown_folding_disabled = 0
let g:vim_markdown_folding_level = 6
let g:vim_markdown_nc_default_kwy_mappings = 0
let g:vim_markdown_toc_autofit = 1
let g:vim_markdown_conceal = 0
let g:vim_markdown_math = 1
let g:vim_markdown_autowrite = 0
let g:vim_markdown_edit_url_in = 'hsplit'
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown']
hook_add = '''
let g:table_mode_corner = '|'
let g:table_mode_always_active = 1
let g:table_mode_syntax = 1
let g:table_mode_auto_align = 1
'''

[[plugins]]
repo = 'scizorman/previm'
depends = ['open-browser.vim']
on_ft = ['markdown']

# Toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# Json
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
