[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/vimproc.vim"


# -----------------------------------------------------------------------------
# Deoplete
# -----------------------------------------------------------------------------
[[plugins]]
repo = "Shougo/neosnippet-snippets"


# -----------------------------------------------------------------------------
# Git
# -----------------------------------------------------------------------------
[[plugins]]
repo = "lambdalisue/gina.vim"
hook_add = "call hook#add#gina#rc()"

[[plugins]]
repo = "airblade/vim-gitgutter"


# -----------------------------------------------------------------------------
# Interface
# -----------------------------------------------------------------------------
[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = "call hook#add#lightline#rc()"

[[plugins]]
repo = "ryanoasis/vim-devicons"


# -----------------------------------------------------------------------------
# Utility
# -----------------------------------------------------------------------------
[[plugins]]
repo = "machakann/vim-sandwich"

[[plugins]]
repo = "Yggdroot/indentLine"


# -----------------------------------------------------------------------------
# Colorscheme
# -----------------------------------------------------------------------------
[[plugins]]
repo = "cocopon/iceberg.vim"

[[plugins]]
repo = "jacoborus/tender.vim"
hook_add = "Gautocmd VimEnter * nested colorscheme tender"
