[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "Shougo/vimproc.vim"


# -----------------------------------------------------------------------------
# Language Server Protocol
# -----------------------------------------------------------------------------
[[plugins]]
repo = "autozimu/LanguageClient-neovim"
rev = "next"
build = "bash install.sh"
hook_add = "call hook#add#LanguageClient#config()"


# -----------------------------------------------------------------------------
# Neosnippet
# -----------------------------------------------------------------------------
[[plugins]]
repo = "Shougo/neosnippet-snippets"


# -----------------------------------------------------------------------------
# Git
# -----------------------------------------------------------------------------
[[plugins]]
repo = "lambdalisue/gina.vim"
hook_add = "call hook#add#gina#config()"

[[plugins]]
repo = "airblade/vim-gitgutter"


# -----------------------------------------------------------------------------
# Interface
# -----------------------------------------------------------------------------
[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = "call hook#add#lightline#config()"

[[plugins]]
repo = "ryanoasis/vim-devicons"


# -----------------------------------------------------------------------------
# Utility
# -----------------------------------------------------------------------------
[[plugins]]
repo = "tpope/vim-surround"
hook_add = """
vmap S <Nop>
"""

[[plugins]]
repo = "Yggdroot/indentLine"


# -----------------------------------------------------------------------------
# Colorscheme
# -----------------------------------------------------------------------------
[[plugins]]
repo = "cocopon/iceberg.vim"

[[plugins]]
repo = "jacoborus/tender.vim"
hook_add = "Gautocmd VimEnter * nested colorscheme tender"
