# Edit utils
[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('nvim')"
# on_cmd = 'Denite'
build = ':UpdateRemotePlugins'
depends = ['neomru.vim', 'neoinclude.vim']
hook_source = 'source $HOME/.vim/rc/plugins/denite.rc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
if = "!has('nvim')"
# on_cmd = 'Unite'
depends = ['neomru.vim', 'neoinclude.vim']
hook_source = 'source $HOME/.vim/rc/unite.rc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'


# Completions
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
bulid = ':UpdateRemotePlugins'
depends = ['neosnippet.vim']
hook_source = '''
  source $HOME/.vim/rc/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "!has('nvim') && has('lua')"
depends = ['neosnippet.vim']
hook_source = '''
  let g:neosnippet#enable_at_startup = 1
  source $HOME/.vim/rc/plugins/neocomplete.rc.vim
''' 

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'h']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1


# Programing utils
[[plugins]]
repo = 'kassio/neoterm'
on_cmd = 'T'
on_ft = ['python']
if = "has('nvim')"
hook_add = '''
  let g:neoterm_autojump = 1
  let g:neoterm_autoinsert = 1
  let g:neoterm_augoscroll = 1
  let g:neoterm_keep_term_open = 0
  let g:neoterm_position = 'vertical'
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
on_ft = ['python']
hook_source = '''
  source $HOME/.vim/rc/plugins/vimquickrun.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
bulid = 'make'

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python', 'javascript', 'html', 'css', 'markdown', 'make', 'vim']
hook_source = '''
  source $HOME/.vim/rc/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'tyru/caw.vim'
on_map = ['<Plug>(caw:hatpos:toggle)', '<Plug>(caw:zeropos:toggle)']

[[plugins]]
repo = 'jsfaint/gen_tags.vim'
on_ft = ['python']
hook_source = '''
  let g:gen_tags#ctags_auto_gen = 1
  let g:gen_tags#gtags_auto_gen = 0
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarTogglek']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']


# Fuzzy Finder
[[plugins]]
repo = 'junegunn/fzf'
bulid = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
on_cmd = [
  'Files',
  'GFiles?',
  'Tags',
]


# Other utils
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']
on_map = ['<plug>NERDTreeToggle', '<plug>NERDTreeTabsFind']
depends = ['nerdtree-git-plugin', 'vim-nerdtree-tabs']
hook_add = '''
  let NERDTreeShowHidden=1
  let NERDTreeIgnore=['\.pyc$', '__pycache__']
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
  let g:nerdtree_tabs_autofind = 0
  nmap <Space>f <plug>NERDTreeTabsToggle<CR>
  nmap <Space>t <plug>NERDTreeTabsFind<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['vim-fugitive']

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = [
  'Git',
  'Gcommit',
  'Gstatus',
  'Gdiff',
  'Gblame',
  'Glog'
]

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = ['<Plug>(openbrowser-smart-search)']
hook_add = '''
  let g:netrw_nogx = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
on_ft = ['markdown']

[[plugins]]
repo = 'Yggdroot/indentLine'
on_cmd = ['IndentLinesToggle']
hook_add = '''
  let g:loaded_indentLine = 1
  nmap <Space>i <C-u>:IndentLinesToggle<CR>
'''


# Syntax
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
hook_add = '''
  let g:markdown_syntax_conceal = 0
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_source = '''
  let g:vim_json_syntax_conceal = 0
  let g:indentLine_noConcealCursor = ""
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['markdown', 'toml', 'help']

[[plugins]]
repo = 'Shougo/context_filetype.vim'


